Repository jenkinsci/extras-executable-war, pull requests merged in 2022-05, with the labels that each got.

#52 EOL `JNLPMain` and `MainDialog`
  src/main/java/JNLPMain.java
  src/main/java/MainDialog.java
Labels: removed

#53 EOL `ColorFormatter`
  src/main/java/ColorFormatter.java
  src/main/java/Main.java
Labels: removed

#55 Explicitly handle InvocationTargetException
  src/main/java/Main.java
Labels: skip-changelog

#56 Fix Checkstyle violations
  src/main/java/LogFileOutputStream.java
  src/main/java/Main.java
Labels: skip-changelog

#57 Update Java 8 EOL date for weekly to June 21 2022
  src/main/java/Main.java
Labels: enhancement

#58 Allow running on Java 17 without --enable-future-java
  src/main/java/Main.java
Labels: enhancement
